version: '5.0'
services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: banbifDb2024
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  api:
    build: .
    ports: 
     - 9000:9000
    environment:
      MONGODB_URL: mongodb://root:banbifDb2024@mongo:27017/banbifDb?authSource=admin
      NAME: BanbifApi
    depends_on:
      - mongo
    volumes:
      - C:/Users/Asus/SistemasOperativos/banbif-backend/Banbif-backend/uploadsFiles:/app/uploadsFiles

volumes:
  mongodata:
    driver: local
